"""The skill catalog: reusable engineering know-how, held by roles.

Skills are composable (``includes``) and never duplicated per agent. Domain
knowledge is not re-written here either: where VeriTriage already ships a
Knowledge Pack (AXI, NoC, UVM, SVA, CDC, formal, DFT, ...), the skill cites it
as a knowledge source, and the integration test proves every cited pack exists.
"""

from __future__ import annotations

from nirmaan.models import KnowledgeSource, KnowledgeSourceKind, Skill


def _src(kind: KnowledgeSourceKind, refs: tuple[str, ...]) -> tuple[KnowledgeSource, ...]:
    return tuple(KnowledgeSource(kind=kind, ref=r, title=r) for r in refs)


def sk(
    id: str,
    name: str,
    domain: str,
    subdomain: str = "",
    *,
    provides: tuple[str, ...] = (),
    includes: tuple[str, ...] = (),
    prereq: tuple[str, ...] = (),
    packs: tuple[str, ...] = (),
    specs: tuple[str, ...] = (),
    standards: tuple[str, ...] = (),
    procedures: tuple[str, ...] = (),
    tools: tuple[str, ...] = (),
    constraints: tuple[str, ...] = (),
    fails: tuple[str, ...] = (),
    valid: tuple[str, ...] = (),
    examples: tuple[str, ...] = (),
) -> Skill:
    return Skill(
        id=id,
        name=name,
        domain=domain,
        subdomain=subdomain,
        provides=provides,
        includes=includes,
        prerequisites=prereq,
        knowledge_sources=(
            _src(KnowledgeSourceKind.VERITRIAGE_PACK, packs)
            + _src(KnowledgeSourceKind.SPECIFICATION, specs)
            + _src(KnowledgeSourceKind.COMPANY_STANDARD, standards)
        ),
        procedures=procedures,
        tools=tools,
        constraints=constraints,
        common_failure_modes=fails,
        validation_criteria=valid,
        examples=examples,
    )


def protocol(id: str, name: str, packs: tuple[str, ...], spec: str, fails: tuple[str, ...]) -> Skill:
    """A protocol skill: knowledge that refines routing, backed by a pack."""
    return sk(
        id, name, "protocols", "interface",
        packs=packs,
        specs=(spec,),
        prereq=("digital_design",),
        procedures=(
            f"Read the {name} specification sections for every channel in scope.",
            "Enumerate handshake, ordering, and response rules as checkable statements.",
        ),
        fails=fails,
        valid=(
            f"Every {name} rule used is cited to the specification.",
            "Ordering and handshake assumptions are written down, not implied.",
        ),
    )


SKILLS: list[Skill] = [
    # --- Foundations ---------------------------------------------------------
    sk("company_methodology", "Nirmaan engineering methodology", "company", "process",
       standards=("NIP-STD-001 Engineering Constitution", "NIP-STD-002 Evidence and Review"),
       procedures=("Trace every task to a requirement.", "Attach evidence before requesting review."),
       fails=("Claiming completion without evidence.", "Self-approving critical work."),
       valid=("Work items trace to a requirement.", "Every claim cites evidence or is marked uncertain.")),
    sk("git", "Git", "software", "version-control", tools=("git.read", "git.write"),
       procedures=("Branch per change.", "Rebase onto mainline before review."),
       fails=("Losing provenance by squashing history blindly.",),
       valid=("History records who changed what and why.",)),
    sk("change_integration", "Change integration", "software", "version-control", provides=("scm.merge",),
       includes=("git",), tools=("git.merge",),
       procedures=("Merge only approved work.", "Confirm the regression gate is green at the merge point."),
       fails=("Merging unreviewed changes.", "Merging on a stale regression result."),
       valid=("Every merged change links its approved task and gate.",)),
    sk("linux", "Linux", "software", "environment",
       procedures=("Script repeatable runs.", "Capture environment in manifests."),
       fails=("Undocumented environment drift.",),
       valid=("Runs reproduce from a clean environment.",)),
    sk("python", "Python", "software", "language",
       procedures=("Write typed, tested scripts.",),
       fails=("Untested automation silently changing results.",),
       valid=("Automation has tests and deterministic output.",)),
    sk("debugging", "Debugging", "engineering", "method",
       procedures=("Reproduce first.", "Bisect.", "Form a hypothesis and name the evidence that would refute it."),
       fails=("Fixing symptoms.", "Confirmation bias."),
       valid=("A root cause is supported by evidence that would otherwise be absent.",)),
    sk("digital_design", "Digital design fundamentals", "hardware", "fundamentals",
       procedures=("Reason about synchronous timing, resets, and state.",),
       fails=("Combinational loops.", "Unintended latches."),
       valid=("Designs are synchronous and reset-deterministic.",)),
    sk("systemverilog", "SystemVerilog", "hardware", "language", prereq=("digital_design",),
       specs=("IEEE 1800-2017",),
       procedures=("Use synthesizable subsets for design.", "Use classes and interfaces for verification."),
       fails=("Simulation/synthesis mismatch.", "Race conditions in testbenches."),
       valid=("Code compiles cleanly with warnings dispositioned.",)),
    sk("technical_writing", "Technical writing", "documentation", "writing",
       provides=("doc.write", "doc.review"), tools=("doc.publish",),
       standards=("NIP-STD-010 Documentation Style",),
       procedures=("Write for the reader's task.", "Keep specs normative and testable."),
       fails=("Ambiguous normative language.", "Docs drifting from RTL."),
       valid=("Every normative statement is testable.", "Document reviewed by a domain owner.")),
    sk("code_review_practice", "Code review practice", "engineering", "review",
       tools=("review.create",),
       procedures=("Review against the spec, not the author's intent.", "Record every finding."),
       fails=("Rubber-stamp approvals.", "Reviewing only the diff, never the context."),
       valid=("Reviews record findings and a verdict.",)),
    # --- Management and leadership (granted by level) -------------------------
    sk("technical_leadership", "Technical leadership", "management", "technical",
       provides=("mgmt.decompose",),
       procedures=("Decompose work into independently reviewable tasks.", "Name owners and reviewers."),
       fails=("Tasks too large to review.", "Unowned interfaces between tasks."),
       valid=("Every task has an owner, reviewer, and completion evidence.",)),
    sk("engineering_management", "Engineering management", "management", "people",
       provides=("mgmt.plan", "mgmt.delegate", "mgmt.track"),
       tools=("task.create", "task.assign", "task.cancel", "approval.grant"),
       procedures=("Plan, delegate, track, unblock, report.", "Escalate cross-team conflicts early."),
       fails=("Doing subordinates' work.", "Hiding blocked work."),
       valid=("Status reports show blockers with their dependency chain.",)),
    sk("executive_leadership", "Executive leadership", "management", "executive",
       provides=("exec.strategy",),
       procedures=("Resolve strategic conflicts with recorded decisions.",),
       fails=("Unrecorded decisions.",),
       valid=("Strategic decisions are recorded with rationale and evidence.",)),
    sk("corporate_governance", "Corporate governance", "management", "governance",
       procedures=("Approve charters and policy changes.",),
       fails=("Policy changes without audit.",),
       valid=("Policy changes are auditable.",)),
    # --- Product and program -------------------------------------------------
    sk("requirements_engineering", "Requirements engineering", "product", "requirements",
       provides=("req.analyze", "req.review", "signoff.requirements"),
       standards=("NIP-STD-003 Requirement Traceability",),
       procedures=("Write atomic, testable requirements.", "Assign each an ID and a verification method."),
       fails=("Untestable requirements.", "Implicit assumptions."),
       valid=("Each requirement has an ID, rationale, and verification method.",)),
    sk("product_strategy", "Product strategy", "product", "strategy", provides=("product.define",),
       procedures=("Define configurations, target markets, and success criteria.",),
       fails=("Feature creep.",), valid=("Scope and non-goals are explicit.",)),
    sk("competitive_analysis", "Competitive analysis", "product", "market", provides=("product.competitive",),
       procedures=("Compare against named alternatives on stated criteria.",),
       fails=("Unsourced comparisons.",), valid=("Every comparison is sourced.",)),
    sk("program_management", "Technical program management", "program", "planning",
       provides=("program.plan", "program.risk"),
       procedures=("Build the milestone and dependency plan.", "Track the critical path."),
       fails=("Plans without dependencies.", "Risks without owners."),
       valid=("Every milestone has entry and exit criteria.",)),
    sk("risk_management", "Risk management", "program", "risk", provides=("program.risk",),
       procedures=("Rate likelihood and impact.", "Assign mitigation owners."),
       fails=("Stale risk registers.",), valid=("Every open risk has an owner and a trigger.",)),
    sk("release_management", "Release management", "program", "release",
       provides=("release.manage", "signoff.release"),
       procedures=("Assemble the release from approved baselines only.",),
       fails=("Releasing unapproved artifacts.",),
       valid=("Every released artifact is approved and traceable.",)),
    sk("project_management", "Project management", "program", "project", provides=("project.plan",),
       procedures=("Plan tasks, track status, report.",),
       fails=("Status without evidence.",), valid=("Status is derived from task state.",)),
    # --- Architecture --------------------------------------------------------
    sk("system_architecture", "System architecture", "architecture", "system",
       provides=("arch.system", "arch.review", "signoff.architecture"), prereq=("digital_design",),
       procedures=("Partition by function, clock, and power.", "Record decisions with alternatives."),
       fails=("Unrecorded architectural decisions.",),
       valid=("Every decision records alternatives considered and rationale.",)),
    sk("ip_architecture", "IP architecture", "architecture", "ip",
       provides=("arch.ip", "arch.review", "signoff.architecture"), includes=("digital_design",),
       procedures=("Define configuration space, interfaces, and integration requirements.",),
       fails=("Configuration combinations never considered.",),
       valid=("Supported configurations are enumerated and bounded.",)),
    sk("noc_architecture", "NoC architecture", "architecture", "interconnect",
       provides=("arch.interconnect", "arch.review"), packs=("noc",),
       procedures=("Choose topology and routing; prove deadlock freedom.", "Size buffers and credits."),
       fails=("Routing deadlock.", "Credit underflow.", "Head-of-line blocking."),
       valid=("Deadlock freedom is argued or proven.", "Credit and buffer sizing is justified.")),
    sk("qos_architecture", "QoS architecture", "architecture", "interconnect", includes=("arbitration",),
       packs=("noc", "performance"),
       procedures=("Define traffic classes, priorities, and starvation bounds.",),
       fails=("Starvation of low-priority traffic.", "Priority inversion."),
       valid=("Starvation bounds are stated and verifiable.",)),
    sk("memory_architecture", "Memory architecture", "architecture", "memory",
       provides=("arch.memory", "arch.review"), packs=("ddr", "hbm"),
       procedures=("Define address maps, hierarchy, and bandwidth budgets.",),
       fails=("Address map overlap.",), valid=("Address map is overlap-free and documented.",)),
    sk("security_architecture", "Security architecture", "architecture", "security",
       provides=("arch.security", "arch.review"), packs=("security",),
       procedures=("Define protection domains and roots of trust.",),
       fails=("Unprotected debug paths.",), valid=("Every asset has a protection mechanism.",)),
    sk("power_architecture", "Power architecture", "architecture", "power",
       provides=("arch.power", "arch.review"), packs=("low-power",),
       procedures=("Define power domains, states, and transitions.",),
       fails=("Missing isolation.",), valid=("Every domain crossing has isolation/retention intent.",)),
    sk("performance_modeling", "Performance modeling", "architecture", "performance",
       provides=("arch.performance",), packs=("performance",), includes=("python",),
       procedures=("Model bandwidth and latency under stated traffic.",),
       fails=("Models with unstated traffic assumptions.",),
       valid=("Model assumptions are explicit and results reproducible.",)),
    sk("software_architecture", "Software architecture", "architecture", "software",
       provides=("arch.software", "arch.review"),
       procedures=("Define the programming model and register interface.",),
       fails=("Unprogrammable hardware features.",), valid=("Programming model covers every feature.",)),
    sk("interface_specification", "Interface specification", "architecture", "interface",
       provides=("arch.interface", "arch.review"), includes=("digital_design",),
       procedures=("Specify signals, channels, parameters, ordering, and error responses.",
                   "Write a register map as data (register_map.json, the nirmaan.models.RegisterMap format): block, "
                   "bus (axi4-lite or apb), addr_width, data_width 32, unmapped response, and each register's name, "
                   "offset, access (rw, ro, wo, w1c), reset, and optional fields (name, lsb, msb, access, reset), "
                   "exactly as the interface spec states them."),
       tools=("regmap.check",),
       fails=("Unspecified error behaviour.", "Ambiguous ordering."),
       valid=("Every channel's ordering and error behaviour is specified.",)),
    sk("rtl_microarchitecture", "RTL microarchitecture", "architecture", "microarchitecture",
       provides=("arch.microarchitecture", "arch.review"), includes=("digital_design",),
       procedures=("Define pipelines, buffers, arbitration, and state at cycle level.",),
       fails=("Underspecified backpressure.", "Unbounded queues."),
       valid=("Every buffer has a depth justification.", "Backpressure is specified end to end.")),
    sk("cpu_microarchitecture", "CPU microarchitecture", "architecture", "cpu", includes=("rtl_microarchitecture",),
       packs=("riscv-privilege", "riscv-memory-model", "riscv-atomics"),
       procedures=("Define pipeline hazards, exceptions, and memory ordering.",),
       fails=("Imprecise exceptions.",), valid=("Memory model conformance is argued.",)),
    sk("gpu_microarchitecture", "GPU microarchitecture", "architecture", "gpu", includes=("rtl_microarchitecture",),
       procedures=("Define SIMT scheduling and memory coalescing.",),
       fails=("Divergence stalls.",), valid=("Occupancy model is documented.",)),
    sk("npu_microarchitecture", "NPU microarchitecture", "architecture", "npu", includes=("rtl_microarchitecture",),
       procedures=("Define dataflow, tiling, and on-chip buffering.",),
       fails=("Bandwidth-bound dataflows.",), valid=("Utilization model covers target networks.",)),
    sk("dsp_microarchitecture", "DSP microarchitecture", "architecture", "dsp", includes=("rtl_microarchitecture",),
       procedures=("Define fixed-point formats and pipelines.",),
       fails=("Overflow without saturation policy.",), valid=("Numeric formats are specified.",)),
    sk("cache_microarchitecture", "Cache microarchitecture", "architecture", "cache",
       includes=("rtl_microarchitecture",), packs=("coherency",),
       procedures=("Define replacement, coherency states, and hazards.",),
       fails=("Illegal coherency transitions.",), valid=("Coherency transitions are enumerated.",)),
    sk("memory_controller_microarchitecture", "Memory controller microarchitecture", "architecture", "memory-controller",
       includes=("rtl_microarchitecture",), packs=("ddr", "hbm"),
       procedures=("Define scheduling, refresh, and timing enforcement.",),
       fails=("Missed refresh.", "Timing parameter violations."),
       valid=("Every JEDEC timing parameter is enforced.",)),
    sk("peripheral_microarchitecture", "Peripheral IP microarchitecture", "architecture", "peripheral",
       includes=("rtl_microarchitecture",), packs=("uart", "spi", "i2c-i3c"),
       procedures=("Define register interface, interrupts, and FIFOs.",),
       fails=("Interrupt races.",), valid=("Interrupt semantics are specified.",)),
    # --- Protocols (knowledge only; backed by VeriTriage packs) ----------------
    protocol("axi", "AMBA AXI", ("axi",), "ARM IHI 0022 (AMBA AXI)",
             ("Handshake deadlock (VALID waiting on READY).", "Out-of-order ID misuse.", "Missing write response.")),
    protocol("ace", "AMBA ACE", ("ace", "coherency"), "ARM IHI 0022 (ACE)", ("Snoop response errors.", "Barrier misordering.")),
    protocol("chi", "AMBA CHI", ("chi",), "ARM IHI 0050 (CHI)", ("Credit starvation.", "Retry protocol misuse.")),
    protocol("apb", "AMBA APB", ("apb",), "ARM IHI 0024 (APB)", ("PREADY stuck low.",)),
    protocol("ahb", "AMBA AHB", ("ahb",), "ARM IHI 0033 (AHB)", ("HREADY stalls.", "Burst boundary violations.")),
    protocol("axi_stream", "AMBA AXI-Stream", ("axi-stream",), "ARM IHI 0051 (AXI4-Stream)", ("Missing TLAST.",)),
    protocol("pcie", "PCI Express", ("pcie",), "PCI Express Base Specification", ("LTSSM stuck.", "Completion timeouts.")),
    protocol("cxl", "Compute Express Link", ("cxl",), "CXL Specification", ("Flex Bus negotiation failure.",)),
    protocol("ddr", "DDR SDRAM", ("ddr",), "JEDEC JESD79", ("Refresh missed.", "tRCD/tRP violations.")),
    protocol("usb", "USB", ("usb",), "USB 2.0 / 3.x Specifications", ("Missing handshake packet.",)),
    protocol("noc_protocol", "NoC packet protocols", ("noc",), "NIP-SPEC-NOC Packet and Flit Format",
             ("Credit underflow.", "Routing deadlock.", "Head-of-line blocking.")),
    protocol("ethernet", "Ethernet", ("ethernet",), "IEEE 802.3", ("FCS errors.", "Block lock loss.")),
    sk("custom_interfaces", "Custom interfaces", "protocols", "interface", includes=("interface_specification",),
       procedures=("Define custom protocols with the same rigor as a standard.",),
       fails=("Undocumented handshakes.",), valid=("Custom protocol has a written, reviewed spec.",)),
    # --- RTL design -------------------------------------------------------------
    sk("rtl_design", "RTL design", "design", "rtl",
       provides=("rtl.implement", "rtl.review", "signoff.rtl"),
       includes=("systemverilog", "digital_design"),
       tools=("git.write", "lint.run", "simulator.run", "synth.run", "formal.run", "formal.cover",
              "regmap.check", "regmap.verify"),
       standards=("NIP-STD-020 RTL Coding Standard",),
       procedures=("Implement from the microarchitecture spec.", "Keep lint clean.", "Write design-intent assertions."),
       fails=("Spec deviations without a recorded decision.", "Latches.", "Reset gaps."),
       valid=("RTL is lint-clean, reviewed, and traceable to the microarchitecture.",),
       examples=("AXI slave interface with outstanding-transaction tracking.",)),
    sk("datapath_design", "Datapath design", "design", "datapath", includes=("rtl_design",),
       procedures=("Pipeline wide datapaths to meet timing.",),
       fails=("Width mismatches.",), valid=("Every width conversion is explicit.",)),
    sk("control_logic_design", "Control logic design", "design", "control", includes=("rtl_design",),
       procedures=("Keep control separable from datapath.",),
       fails=("Deadlocking control.",), valid=("Control has no unreachable or stuck states.",)),
    sk("fsm_design", "FSM design", "design", "fsm", includes=("rtl_design",),
       procedures=("Enumerate states and legal transitions.",),
       fails=("Unreachable or trap states.",), valid=("Every state is reachable and exits.",)),
    sk("pipeline_design", "Pipeline design", "design", "pipeline", includes=("rtl_design",),
       procedures=("Specify stall and flush behaviour.",),
       fails=("Bubbles lost on stall.",), valid=("Stall/flush semantics are verified.",)),
    sk("memory_design", "Memory design", "design", "memory", includes=("rtl_design",),
       procedures=("Wrap memories with test and power hooks.",),
       fails=("Read-during-write ambiguity.",), valid=("Memory semantics are specified.",)),
    sk("arithmetic_design", "Arithmetic design", "design", "arithmetic", includes=("rtl_design",),
       procedures=("Specify rounding and overflow.",),
       fails=("Silent overflow.",), valid=("Numeric behaviour matches a reference model.",)),
    sk("interconnect_design", "Interconnect RTL design", "design", "interconnect",
       includes=("rtl_design", "arbitration", "buffering_flow_control", "noc_protocol"), packs=("noc", "axi"),
       procedures=("Implement routing, arbitration, and flow control.",),
       fails=("Credit leaks.", "Deadlock."), valid=("Flow control is credit-correct.",)),
    sk("arbitration", "Arbitration", "design", "arbitration", packs=("noc",),
       procedures=("Choose round-robin, weighted, or priority arbitration with starvation bounds.",),
       fails=("Starvation.", "Unfair grants under backpressure."),
       valid=("Fairness and starvation bounds are verified.",)),
    sk("buffering_flow_control", "Buffering and flow control", "design", "flow-control", packs=("noc",),
       procedures=("Size FIFOs from latency and throughput.",),
       fails=("Overflow.", "Underflow."), valid=("FIFO sizing is justified.",)),
    sk("rtl_lint", "RTL lint", "design", "quality", provides=("rtl.lint",), includes=("coding_standards",),
       tools=("lint.run",), procedures=("Run lint; fix or waive with rationale.",),
       fails=("Blanket waivers.",), valid=("Every waiver has an approved rationale.",)),
    sk("coding_standards", "Coding standards", "design", "quality", standards=("NIP-STD-020 RTL Coding Standard",),
       procedures=("Apply naming, reset, and clocking rules.",),
       fails=("Inconsistent reset style.",), valid=("Code conforms to NIP-STD-020.",)),
    sk("synthesis_awareness", "Synthesis awareness", "design", "quality", provides=("rtl.quality",),
       procedures=("Estimate logic depth and area.", "Avoid unsynthesizable constructs."),
       fails=("Timing surprises at synthesis.",), valid=("Quality report flags depth and area risks.",)),
    sk("change_impact_analysis", "Change impact analysis", "design", "change", provides=("rtl.impact",),
       tools=("code.search", "git.read"),
       procedures=("Trace a change to affected modules, interfaces, tests, and docs.",),
       fails=("Missed downstream consumers.",), valid=("Impact lists modules, tests, and docs affected.",)),
    sk("cdc_design", "CDC-safe design", "design", "cdc", provides=("rtl.cdc_design",), packs=("cdc", "reset-clocking"),
       tools=("lint.run", "simulator.run", "synth.run", "formal.run", "formal.cover"),  # M29: the RTL gates
       procedures=("Use approved synchronizers.", "Gray-code multi-bit crossings."),
       fails=("Unsynchronized crossings.", "Reconvergence."),
       valid=("Every crossing uses an approved structure.",)),
    sk("reset_design", "Reset design", "design", "reset", packs=("reset-clocking",),
       procedures=("Define reset domains and sequencing.",),
       fails=("Reset deassertion races.",), valid=("Reset sequencing is documented and checked.",)),
    sk("low_power_design", "Low-power design", "design", "power", provides=("rtl.power_intent",), packs=("low-power",),
       procedures=("Write UPF; clock-gate; isolate and retain.",),
       fails=("Missing isolation cells.",), valid=("Power intent passes static checks.",)),
    sk("ip_integration", "IP integration and packaging", "design", "integration", provides=("rtl.integrate",),
       includes=("rtl_design",), procedures=("Package configured views, collateral, and integration guides.",),
       fails=("Unpackaged collateral.",), valid=("Package builds from a clean checkout.",)),
    sk("design_automation", "Design automation", "design", "automation", provides=("automation.develop",),
       includes=("python", "linux"), procedures=("Automate repeatable flows with tests.",),
       fails=("Brittle scripts.",), valid=("Automation is tested and versioned.",)),
    # --- Verification ------------------------------------------------------------
    sk("uvm", "UVM", "verification", "methodology", provides=("dv.testbench",), includes=("systemverilog",),
       packs=("uvm", "uvm-phasing", "uvm-tlm", "uvm-ral"), specs=("IEEE 1800.2 (UVM)",),
       tools=("simulator.run", "test.run"),
       procedures=("Build agents, scoreboards, and reference models.", "Use RAL for registers."),
       fails=("Objection leaks.", "Unconnected TLM ports.", "RAL mirror mismatches."),
       valid=("Environment compiles, runs a smoke test, and checks every interface.",)),
    sk("verification_architecture", "Verification architecture", "verification", "architecture",
       provides=("dv.architecture",), includes=("uvm", "verification_planning"),
       procedures=("Choose simulation/formal split and reuse strategy.",),
       fails=("Unverifiable features.",), valid=("Every feature has a verification method.",)),
    sk("verification_planning", "Verification planning", "verification", "planning",
       provides=("dv.plan", "dv.review"), packs=("coverage",), tools=("vplan.check",),
       procedures=("Map requirements to features, tests, assertions, and coverage.",),
       fails=("Plans not traceable to requirements.",),
       valid=("Every requirement maps to at least one verification item.",)),
    sk("directed_testing", "Directed testing", "verification", "stimulus", provides=("dv.directed_tests",),
       includes=("systemverilog",), tools=("test.run",),
       procedures=("Write focused tests for specified scenarios.",),
       fails=("Tests that cannot fail.",), valid=("Each test checks an expected outcome.",)),
    sk("constrained_random", "Constrained-random verification", "verification", "stimulus",
       provides=("dv.random_tests",), includes=("uvm",), tools=("test.run", "regression.run"),
       procedures=("Write sequences with meaningful constraints.", "Close with coverage."),
       fails=("Over-constrained stimulus.",), valid=("Stimulus reaches coverage goals.",)),
    sk("sva", "SystemVerilog Assertions", "verification", "assertions", provides=("dv.assertions",),
       includes=("systemverilog",), packs=("sva",),
       procedures=("Write protocol and design-intent assertions with cover properties.",),
       fails=("Vacuous assertions.",), valid=("Every assertion has a non-vacuous cover.",)),
    sk("vip_integration", "VIP integration", "verification", "vip", provides=("dv.vip",), includes=("uvm",),
       procedures=("Configure VIP to the interface spec.",),
       fails=("VIP configured to defaults, not the spec.",), valid=("VIP configuration traces to the spec.",)),
    sk("functional_coverage", "Functional coverage", "verification", "coverage", provides=("dv.coverage",),
       packs=("coverage",), tools=("coverage.read",),
       procedures=("Model coverage from the plan.", "Exclude with rationale."),
       fails=("Coverage holes hidden by exclusions.",), valid=("Every exclusion is reviewed.",)),
    sk("code_coverage", "Code coverage", "verification", "coverage", provides=("dv.coverage",), tools=("coverage.read",),
       procedures=("Merge and analyze line, toggle, FSM, and branch coverage.",),
       fails=("Dead code counted as covered.",), valid=("Unreachable code is justified.",)),
    sk("assertion_coverage", "Assertion coverage", "verification", "coverage", provides=("dv.coverage",), packs=("sva",),
       procedures=("Track assertion firing and cover completion.",),
       fails=("Assertions that never evaluate.",), valid=("Every assertion evaluated non-vacuously.",)),
    sk("regression_management", "Regression management", "verification", "regression", provides=("dv.regression",),
       tools=("regression.run", "veritriage.investigate"),
       procedures=("Run regressions, track pass rates, triage failures through VeriTriage.",),
       fails=("Flaky tests ignored.",), valid=("Every failure is triaged or tracked.",)),
    sk("failure_triage", "Failure triage", "verification", "debug", provides=("debug.triage",),
       tools=("veritriage.investigate", "veritriage.explain_log"), packs=("uvm", "sva"),
       procedures=("Run VeriTriage over the failing artifacts.", "Classify with evidence, not intuition."),
       fails=("Classifying from the first error line only.",),
       valid=("Triage cites a VeriTriage session and its evidence nodes.",)),
    sk("log_analysis", "Log analysis", "verification", "debug", provides=("debug.triage",),
       tools=("veritriage.explain_log", "veritriage.investigate"),
       procedures=("Parse logs deterministically before reasoning.",),
       fails=("Grepping for the first ERROR.",), valid=("Findings cite log lines.",)),
    sk("waveform_debug", "Waveform analysis", "verification", "debug", provides=("debug.root_cause",),
       tools=("waveform.inspect",), procedures=("Trace handshakes and state machines in waveforms.",),
       fails=("Reading the wrong clock domain.",), valid=("Root cause cites signals and times.",)),
    sk("root_cause_analysis", "Root-cause analysis", "verification", "debug",
       provides=("debug.root_cause", "debug.review"), includes=("debugging",), packs=("uvm", "sva"),
       tools=("veritriage.investigate",),
       procedures=("Rank competing hypotheses.", "Name the evidence that would refute each."),
       fails=("Single-hypothesis tunnel vision.",),
       valid=("The conclusion names its evidence and the alternatives it rejects.",)),
    sk("regression_intelligence", "Regression intelligence", "verification", "debug", provides=("debug.triage",),
       tools=("veritriage.investigate",),
       procedures=("Check whether a failure was seen before and what fixed it.",),
       fails=("Re-debugging known failures.",), valid=("Similar historical failures are checked.",)),
    sk("formal_verification", "Formal verification", "verification", "formal",
       provides=("formal.prove", "formal.review"), includes=("sva",), packs=("formal", "sva"), tools=("formal.run", "formal.cover"),
       procedures=("Constrain inputs minimally.", "Check vacuity and bounds."),
       fails=("Over-constrained proofs.", "Vacuous passes.", "Inconclusive bounds reported as proofs."),
       valid=("Every proof is non-vacuous and states its bound or completeness.",)),
    sk("model_checking", "Model checking", "verification", "formal", provides=("formal.prove",),
       includes=("formal_verification",), procedures=("Use abstraction to reach full proofs.",),
       fails=("State explosion.",), valid=("Abstractions are reviewed.",)),
    sk("equivalence_checking", "Equivalence checking", "verification", "formal", provides=("formal.equivalence",),
       tools=("equivalence.run",), procedures=("Map and compare implementations.",),
       fails=("Unmapped points hidden.",), valid=("All compare points map.",)),
    sk("formal_coverage", "Formal coverage", "verification", "formal", provides=("formal.prove",),
       packs=("formal",), procedures=("Measure proof core and reachability.",),
       fails=("Unreachable covers ignored.",), valid=("Every unreachable cover is explained.",)),
    sk("cdc_verification", "CDC/RDC verification", "verification", "cdc",
       provides=("cdc.verify", "cdc.review"), packs=("cdc", "reset-clocking"), tools=("cdc.run",),
       procedures=("Run structural and functional CDC/RDC.", "Waive only with review."),
       fails=("Blanket waivers.", "Missed reconvergence."),
       valid=("Every violation is fixed or waived with an approved rationale.",)),
    sk("security_verification", "Security verification", "verification", "security", provides=("secver.verify",),
       packs=("security",), procedures=("Verify access control and absence of leaks.",),
       fails=("Only positive testing.",), valid=("Negative (attack) scenarios are covered.",)),
    sk("verification_signoff", "Verification signoff", "verification", "signoff",
       provides=("dv.closure", "dv.review", "signoff.verification"),
       procedures=("Check plan, coverage, regression, formal, and waivers against criteria.",),
       fails=("Signing off on percentages without looking at holes.",),
       valid=("Signoff cites evidence for every criterion.",)),
    # --- Implementation ----------------------------------------------------------
    sk("synthesis", "Synthesis", "implementation", "synthesis", provides=("synth.run",), tools=("synth.run",),
       procedures=("Synthesize under constraints; review QoR.",),
       fails=("Unconstrained paths.",), valid=("QoR report reviewed; no unconstrained paths.",)),
    sk("sta", "Static timing analysis", "implementation", "timing", provides=("sta.analyze", "sta.review"),
       includes=("timing_constraints",), tools=("sta.run",),
       procedures=("Analyze setup and hold across MCMM.", "Classify violations by root cause."),
       fails=("Exceptions masking real paths.",), valid=("Every exception is justified.",)),
    sk("timing_constraints", "Timing constraints", "implementation", "timing", provides=("sta.constraints",),
       procedures=("Write SDC for clocks, IO, and exceptions.",),
       fails=("Over-broad false paths.",), valid=("Constraints are reviewed and validated.",)),
    sk("floorplanning", "Floorplanning", "implementation", "physical", provides=("pd.floorplan",), tools=("pnr.run",),
       procedures=("Place macros and define regions.",), fails=("Congested floorplans.",),
       valid=("Floorplan meets utilization targets.",)),
    sk("power_planning", "Power planning", "implementation", "physical", provides=("pd.power_plan",), tools=("pnr.run",),
       procedures=("Design the grid for IR and EM.",), fails=("Weak grids.",), valid=("Grid meets IR targets.",)),
    sk("place_and_route", "Placement, CTS, and routing", "implementation", "physical",
       provides=("pd.place_route", "pd.review"), tools=("pnr.run",),
       procedures=("Place, build clock trees, route, and optimize.",),
       fails=("Clock skew.", "Routing congestion."), valid=("Design routes clean and meets timing.",)),
    sk("power_analysis", "Power analysis", "implementation", "power", provides=("power.analyze",), tools=("power.run",),
       procedures=("Analyze dynamic and leakage power, IR drop, and EM.",),
       fails=("Vectorless-only estimates.",), valid=("Power analysis states its activity source.",)),
    sk("physical_verification", "Physical verification", "implementation", "signoff",
       provides=("pd.signoff_checks",), tools=("pv.run",),
       procedures=("Run DRC, LVS, ERC, antenna, and density.",),
       fails=("Waiving DRC without foundry approval.",), valid=("Clean or foundry-waived.",)),
    sk("implementation_signoff", "Implementation signoff", "implementation", "signoff",
       provides=("signoff.implementation",),
       procedures=("Check timing, power, and physical signoff criteria.",),
       fails=("Signing off with open exceptions.",), valid=("Every criterion cites evidence.",)),
    # --- DFT -----------------------------------------------------------------------
    sk("dft_architecture", "DFT architecture", "dft", "architecture", provides=("dft.review",), packs=("dft", "jtag"),
       procedures=("Define test access, compression, and coverage targets.",),
       fails=("Untestable logic.",), valid=("Coverage targets are stated.",)),
    sk("scan_design", "Scan design", "dft", "scan", provides=("dft.insert",), packs=("dft",),
       tools=("dft.run", "dft.scan_insert", "dft.check", "dft.scan_sim", "dft.atpg", "dft.atpg_transition"),
       procedures=("Insert and balance scan chains.", "Check testability rules on the scan netlist.",
                   "Shift and capture through every chain in simulation before review."),
       fails=("Broken scan chains.", "Flops left off the chain.", "Gated or generated clocks."),
       valid=("Chain integrity verified.", "Every flop is on a chain.")),
    sk("atpg", "ATPG", "dft", "atpg", provides=("dft.atpg",), packs=("dft",), tools=("dft.run", "dft.atpg", "dft.atpg_transition"),
       procedures=("Generate and grade patterns.",), fails=("Low fault coverage.",),
       valid=("Fault coverage meets target.",)),
    sk("mbist", "Memory BIST", "dft", "mbist", provides=("dft.mbist",), packs=("dft",),
       tools=("dft.run", "dft.mbist"),
       procedures=("Insert MBIST and verify signatures.",), fails=("Signature mismatches.",),
       valid=("MBIST passes on all memories.",)),
    sk("lbist", "Logic BIST", "dft", "lbist", provides=("dft.insert",), packs=("dft",),
       procedures=("Insert LBIST with X-bounding.",), fails=("X-contaminated signatures.",),
       valid=("Signatures are X-free.",)),
    sk("jtag", "JTAG", "dft", "jtag", provides=("dft.insert",), packs=("jtag",),
       procedures=("Implement TAP and boundary scan.",), fails=("TAP state errors.",),
       valid=("TAP compliance checked.",)),
    sk("test_compression", "Test compression", "dft", "compression", provides=("dft.insert",),
       procedures=("Configure compression ratios.",), fails=("Coverage loss from compression.",),
       valid=("Compression preserves coverage.",)),
    sk("fault_modeling", "Fault modeling", "dft", "faults", provides=("dft.atpg",), tools=("dft.atpg", "dft.atpg_transition"),
       procedures=("Select stuck-at, transition, and cell-aware models.",),
       fails=("Missing fault models.",), valid=("Fault models match the quality target.",)),
    sk("dft_verification", "DFT verification", "dft", "verification", provides=("dft.verify",),
       packs=("dft", "x-propagation"), tools=("dft.check", "dft.scan_sim"),
       procedures=("Simulate patterns and test modes.",),
       fails=("Test-mode X propagation.",), valid=("Patterns pass in simulation.",)),
    # --- Software ------------------------------------------------------------------
    sk("c_programming", "C programming", "software", "language", tools=("compiler.run",),
       procedures=("Write MISRA-aware embedded C.",), fails=("Undefined behaviour.",),
       valid=("Static analysis is clean.",)),
    sk("embedded_firmware", "Embedded firmware", "software", "firmware", provides=("fw.develop", "sw.review"),
       includes=("c_programming",), procedures=("Write boot, HAL, and BSP code.",),
       fails=("Hardware assumptions not in the spec.",), valid=("Firmware runs on the reference model.",)),
    sk("device_drivers", "Device drivers", "software", "drivers", provides=("sw.driver", "fw.driver"),
       includes=("c_programming",), tools=("fw.build", "fw.test", "fw.cross_build", "fw.soc_test"),
       procedures=("Implement drivers from the programming model.",
                   "Write the register map header from the approved interface specification, never from the RTL.",
                   "When an approved register map exists, include <block>_map.h and do not write it: the firmware "
                   "tools generate it from the map (offsets, resets, field _SHIFT, _MASK, _RESET, _GET and _SET), "
                   "and a header you write instead must agree with it.",
                   "Reach the hardware only through nirmaan_hal.h: hal->read32(ctx, offset, &value) and "
                   "hal->write32(ctx, offset, value, strobe) return the bus response (NIRMAAN_BUS_OKAY, "
                   "NIRMAAN_BUS_SLVERR, ...); return every error to the caller.",
                   "Write driver tests in C: define void nirmaan_fw_test(const nirmaan_hal *hal) and report "
                   "each check with nirmaan_test_result(name, passed, detail).",
                   "Test reset values, every register written then read back (write all before reading any), "
                   "byte-lane writes, and the error response for an unmapped access."),
       constraints=("C11 that compiles with -Wall -Wextra -Werror -pedantic.",
                    "No hardware address is dereferenced outside the HAL."),
       fails=("Race conditions.", "Register offsets that alias.", "Bus errors swallowed by the driver.",
              "Tests that cannot fail."),
       valid=("Driver passes diagnostics.",
              "Builds clean and passes its tests against the approved RTL (fw.build, fw.test).")),
    sk("register_programming", "Register programming", "software", "registers",
       provides=("sw.register_programming",), packs=("uvm-ral",),
       procedures=("Write programming sequences from the register spec.",),
       fails=("Sequences relying on undocumented behaviour.",), valid=("Sequences match the register spec.",)),
    sk("diagnostics_software", "Diagnostics", "software", "diagnostics", provides=("sw.diagnostics",),
       includes=("c_programming",), procedures=("Write self-checking diagnostics.",),
       fails=("Diagnostics that cannot fail.",), valid=("Diagnostics detect injected faults.",)),
    sk("developer_tools", "Developer tools", "software", "tools", provides=("sw.tools",),
       includes=("python",), procedures=("Build SDKs, compilers, debuggers, and utilities.",),
       fails=("Untested toolchains.",), valid=("Tools have regression tests.",)),
    # --- Security ------------------------------------------------------------------
    sk("threat_modeling", "Threat modeling", "security", "threats",
       provides=("security.threat_model", "security.review"), packs=("security",),
       procedures=("Enumerate assets, adversaries, and mitigations.",),
       fails=("Ignoring debug and test paths.",), valid=("Every asset has a threat and mitigation.",)),
    sk("hardware_security", "Hardware security", "security", "hardware",
       provides=("security.review",), packs=("security",),
       procedures=("Review isolation, fuses, and debug locking.",),
       fails=("Side channels ignored.",), valid=("Security review has recorded findings.",)),
    sk("secure_boot", "Secure boot", "security", "boot", provides=("security.review",), packs=("security",),
       procedures=("Verify the chain of trust.",), fails=("Unverified boot stages.",),
       valid=("Every stage is authenticated.",)),
    sk("cryptography", "Cryptography", "security", "crypto", provides=("security.crypto",),
       procedures=("Specify algorithms, modes, and key handling.",),
       fails=("Key material exposure.",), valid=("Crypto blocks have known-answer tests.",)),
    sk("vulnerability_management", "Vulnerability management", "security", "vulnerabilities",
       provides=("security.vulnerability",), procedures=("Track, rate, and remediate vulnerabilities.",),
       fails=("Untracked findings.",), valid=("Every finding has an owner and status.",)),
    # --- Infrastructure ------------------------------------------------------------
    sk("ci_cd", "CI/CD", "infrastructure", "ci", provides=("infra.ci",), includes=("git", "linux"),
       tools=("ci.configure",), procedures=("Automate build, lint, and smoke tests on every change.",),
       fails=("Flaky pipelines.",), valid=("Pipeline is deterministic.",)),
    sk("build_systems", "Build systems", "infrastructure", "build", provides=("infra.ci",), includes=("linux",),
       procedures=("Make builds hermetic and cached.",), fails=("Non-hermetic builds.",),
       valid=("Builds reproduce bit-for-bit.",)),
    sk("regression_infrastructure", "Regression infrastructure", "infrastructure", "regression",
       provides=("infra.regression",), includes=("linux",), tools=("farm.submit",),
       procedures=("Schedule, shard, and archive regressions.",), fails=("Lost logs.",),
       valid=("Every run's artifacts are archived.",)),
    sk("eda_environment", "EDA environment", "infrastructure", "eda", provides=("infra.eda_environment",),
       includes=("linux",), procedures=("Version tools and licenses.",), fails=("Tool version drift.",),
       valid=("Tool versions are pinned per project.",)),
    sk("compute_cloud", "Compute and cloud", "infrastructure", "compute", provides=("infra.compute",),
       includes=("linux",), procedures=("Provision compute, storage, and containers.",),
       fails=("Unbounded cost.",), valid=("Capacity is monitored.",)),
    sk("artifact_management", "Artifact management", "infrastructure", "artifacts", provides=("infra.ci",),
       procedures=("Store build and release artifacts immutably.",), fails=("Mutable artifacts.",),
       valid=("Artifacts are content-addressed.",)),
    sk("monitoring", "Monitoring", "infrastructure", "observability", provides=("infra.compute",),
       procedures=("Monitor farms, licenses, and pipelines.",), fails=("Silent outages.",),
       valid=("Alerts have owners.",)),
    # --- Documentation -------------------------------------------------------------
    sk("register_documentation", "Register documentation", "documentation", "registers",
       provides=("doc.registers",), includes=("technical_writing",),
       procedures=("Generate register docs from the single source of truth.",),
       fails=("Hand-maintained register tables.",), valid=("Docs generated from the register source.",)),
    sk("user_documentation", "User documentation", "documentation", "manuals", includes=("technical_writing",),
       procedures=("Write task-oriented guides validated against the product.",),
       fails=("Guides describing intended rather than actual behaviour.",),
       valid=("Every procedure in the guide has been exercised.",)),
    sk("specification_writing", "Specification writing", "documentation", "specifications",
       includes=("technical_writing",), procedures=("Use normative language consistently.",),
       fails=("Mixing informative and normative text.",), valid=("Normative statements are marked.",)),
    # --- Quality ---------------------------------------------------------------------
    sk("traceability", "Traceability", "quality", "traceability", provides=("quality.traceability",),
       tools=("trace.read",), standards=("NIP-STD-003 Requirement Traceability",),
       procedures=("Link requirements to design, verification, and evidence.",),
       fails=("Orphan requirements.",), valid=("Every requirement has verification evidence.",)),
    sk("design_review_facilitation", "Design review facilitation", "quality", "reviews",
       provides=("quality.design_review",), procedures=("Run reviews with entry and exit criteria.",),
       fails=("Reviews without recorded outcomes.",), valid=("Every review records a verdict.",)),
    sk("engineering_audit", "Engineering audit", "quality", "audit", provides=("quality.audit",),
       tools=("trace.read",), procedures=("Audit evidence against claims.",),
       fails=("Auditing process, not evidence.",), valid=("Audit samples evidence directly.",)),
    sk("configuration_management", "Configuration management", "quality", "configuration",
       provides=("quality.configuration",), includes=("git",),
       procedures=("Baseline configurations and control change.",), fails=("Unbaselined releases.",),
       valid=("Every release has a baseline.",)),
    sk("compliance", "Compliance", "quality", "compliance", provides=("quality.audit",),
       procedures=("Map process to standards (e.g. ISO 26262).",), fails=("Paper compliance.",),
       valid=("Compliance claims cite evidence.",)),
    sk("release_quality", "Release quality", "quality", "release", provides=("signoff.quality",),
       procedures=("Check release criteria and open issues.",), fails=("Shipping with open criticals.",),
       valid=("Release criteria all cite evidence.",)),
    # --- Business (placeholders stay structurally whole) ------------------------------
    sk("business_operations", "Business operations", "business", "operations",
       procedures=("Operate the function to company policy.",), fails=("Undocumented decisions.",),
       valid=("Decisions are recorded.",)),
]
